# Show / Hide plots
plot = true

# [Optional] Seed for RNG. Comment it out for randomness, or set an integer for determinism
seed = 20241006
learning_rate = 0.1
beta = 0.4
train_proportion = 0.7
epoch=10000
noise_val=0.0


[and]
input = [[-1,1],[1,-1],[-1,-1],[1,1]]
output = [-1,-1,-1,1]

[xor]
input = [[-1,1],[1,-1],[-1,-1],[1,1]]
output = [1,1,-1,-1]

[single_layer.linear_non_linear]
path = "datasets/TP3-ej2-conjunto.csv"
# Activation function: 'tanh' or 'logistic'
activation_function = "tanh"

[multi_layer]
# Choose one between 'online', 'minibatch' and 'batch'
training_style = 'minibatch'
# If 'minibatch' is chosen, a batch_size is needed
batch_size = 2

[multi_layer.parity_discrimination]
path = "datasets/TP3-ej3-digitos.txt"
# Activation function: 'tanh' or 'logistic'
activation_function = "logistic"

[multi_layer.digit_discrimination]
# Activation function: 'tanh' or 'logistic'
activation_function = "logistic"

[multi_layer.mnist]
path="datasets/mnist.npz"

[multi_layer.momentum]
# Usually 0.8 or 0.9. Must be in range [0, 1]
alpha=0.8

[multi_layer.adam]
beta1=0.9
beta2=0.999
epsilon=1e-8
