# Show / Hide plots
plot = true

# [Optional] Seed for RNG. Comment it out for randomness, or set an integer for determinism
seed = 13202409176
learning_rate = 0.001
beta = 0.4
train_proportion = 0.7
epoch=100000


[and]
input = [[-1,1],[1,-1],[-1,-1],[1,1]]
output = [-1,-1,-1,1]

[xor]
input = [[-1,1],[1,-1],[-1,-1],[1,1]]
output = [1,1,-1,-1]

[single_layer.linear_non_linear]
path = "TP3/datasets/TP3-ej2-conjunto.csv"
# Activation function: tanh or logistic
activation_function = "tanh"

[multi_layer.parity_discrimination]
path = "TP3/datasets/TP3-ej3-digitos.txt"

[multi_layer.digit_discrimination]
noise_val=0.0

[multi_layer.mnist]
path="TP3/datasets/mnist.npz"
