[kohonen]
k = 3
initial_radius = 9
epochs_multiplier = 1000
set_initial_weights_from_dataset = true
distance = "euclidean"  # O "exponential"

[oja]
epochs = 10000
learning_rate = 0.001
weights_low = -0.5
weights_high = 0.5
