# Show / Hide plots
plot = true

# [Optional] Seed for RNG. Comment it out for randomness, or set an integer for determinism
seed = 20241001

learning_rate = 0.1
beta = 0.4
epsilon=0.0000001
epochs = 25000

batch_size = 10

